version: '3.4'
services:
  web:
    image: okteto/django:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  
  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
