version: '3.4'
services:
  web:
    image: okteto/django:latest
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      
  postgres:
    container_name: okteto-db
    image: "postgres:12.2-alpine"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
