version: '3.4'
services:
  web:
    image: okteto/django:latest
    build: .
    command: ["django-admin", "startproject", "principal", "./app"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      

  db:
    image: postgres:9.4
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ifrs
    ports:
      - "5432:5432"
