version: '3.4'
services:
  web:
    image: okteto/django:latest
    container_name: web
    networks: 
      - django-network
    build: .
    public: true
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      
  db:
    image: postgres:9.4
    container_name: db
    networks: 
      - django-network
    public: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
networks: 
    django-network:
        driver: bridge
