version: '3.4'
services:
  web:
    image: okteto/django:latest
    container_name: web
    build: 
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8080"
